### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by giovannicaligaris** [artemanufrij/playmyvideos#11]
Is there a fullscreen button? if not, can we have one?

I tried F11 and it didn't work.

**Comment by artemanufrij** [comment]
F11 should work.... I will check it tonight.

**Comment by artemanufrij** [comment]
I checked F11 function on couple systems multiple times. it worked always. Could you give me feedback does it work on your system?

**Comment by giovannicaligaris** [comment]
It's working now

**Comment by artemanufrij** [comment]
@giovannicaligaris thanks for testing. I'm going to close this issue
