### ISSUE TITLE
Could you add a subtitle option ?

### ISSUE THREAD

**Issue by papou84** [artemanufrij/playmyvideos#14]
This app is great and would be a lot better if it could be possible to add some subtitles from a .srt file to the video.
Thanks a lot for your app

**Comment by artemanufrij** [comment]
@papou84 it's already exists: you subtitle file should just have same name as your video file:

`my video.mkv` -> `my video.mkv.srt` or `my video.srt`

![bildschirmfoto von 2018-01-26 22 31 42](https://user-images.githubusercontent.com/16517095/35461642-f533f156-02e8-11e8-9a49-10c7dc151080.png)

**Comment by papou84** [comment]
Thanks for your answer
Not working for me with :  cold.case.1x11.hubris.hdtv.xvid-fov.srt 
and                                    cold.case.1x11.hubris.hdtv.xvid-fov.avi

Then i thought maybe it is too long.
and i tried with : cold.case.1x11.hubris.avi the same with .srt
and still didn't work.

And could you ad a volume controller to the app ?

**Comment by artemanufrij** [comment]
@papou84  could you try to rename `cold.case.1x11.hubris.hdtv.xvid-fov.srt` to `cold.case.1x11.hubris.hdtv.xvid-fov.avi.srt`

**Comment by papou84** [comment]
It still not working, i tried with those names.

**Comment by papou84** [comment]
I can choose the subtitle but nothing appear on both case

**Comment by papou84** [comment]
![capture d ecran du 2018-01-27 13 34 36](https://user-images.githubusercontent.com/28159992/35471993-dd6f024e-0366-11e8-847d-4b06d55f1b73.png)

**Comment by artemanufrij** [comment]
@papou84 ah ok... you see an item in the choose box, but nothing happens if you choose one - right?

**Comment by papou84** [comment]
yes exactly

**Comment by artemanufrij** [comment]
@papou84 could you build and test current master branch please? I think I found the reason

**Comment by papou84** [comment]
if you tell me step by step i could do that.

**Comment by artemanufrij** [comment]
https://github.com/artemanufrij/playmyvideos#install-from-github

**Comment by papou84** [comment]
ok i'm trying it

**Comment by papou84** [comment]
It will take some time as i have to install all dependencies

**Comment by artemanufrij** [comment]
don't worry :smile:

**Comment by papou84** [comment]
![capture d ecran du 2018-01-27 14 12 11](https://user-images.githubusercontent.com/28159992/35472261-1ff51036-036c-11e8-80c9-268887f6baa9.png)

**Comment by papou84** [comment]
Working just fine

**Comment by papou84** [comment]
Thanks a lot,

**Comment by artemanufrij** [comment]
Thanks for helping. I will push new release tonight

**Comment by papou84** [comment]
Great
