### ISSUE TITLE
Need help with translation ?

### ISSUE THREAD

**Issue by papou84** [artemanufrij/playmyvideos#16]
There is a few things that are not translated in French and i could help with Italian as well

**Comment by artemanufrij** [comment]
@papou84 It would be very helpful! you can use https://poedit.net/ for translating

**Comment by papou84** [comment]
is there a PO projet already existing ?

**Comment by papou84** [comment]
Once it's translated where should i send it ?

**Comment by artemanufrij** [comment]
you can create a PR or zip the po file and just DnD it into conversation here

**Comment by papou84** [comment]
and i added a word in the PO file directly.

**Comment by papou84** [comment]
[Documents.zip](https://github.com/artemanufrij/playmyvideos/files/1682457/Documents.zip)

**Comment by artemanufrij** [comment]
if you import both files into (poedit), so you can just save it after editing.

**Comment by papou84** [comment]
Ok but not sure i understand.

**Comment by papou84** [comment]
you need only one file ?

**Comment by artemanufrij** [comment]
I guess just .po

**Comment by papou84** [comment]
Okay, sorry now i understand.
Great !!!

**Comment by artemanufrij** [comment]
here is an example:
https://github.com/artemanufrij/playmyvideos/blob/51fd7efd52cf9e627cf5bf20471d46a6fb65c9dd/po/nl.po

**Comment by papou84** [comment]
[fr_FR.po.zip](https://github.com/artemanufrij/playmyvideos/files/1682518/fr_FR.po.zip)
I added a corrected few things on this one

**Comment by artemanufrij** [comment]
I will check it when I'm back home...

**Comment by artemanufrij** [comment]
@papou84 I pushed new version into master branch. Could you test it please?

**Comment by papou84** [comment]
Works fine for the translation, there's is still some uppercase missing in English.
 And could you push as well the Italian version please ?

**Comment by artemanufrij** [comment]
just open `it.po` in poedit.net
![bildschirmfoto von 2018-01-31 22 22 09](https://user-images.githubusercontent.com/16517095/35648199-3bdffc86-06d5-11e8-974b-c92657d507fd.png)

**Comment by papou84** [comment]
[it.po.zip](https://github.com/artemanufrij/playmyvideos/files/1683431/it.po.zip)
Should work now.

**Comment by artemanufrij** [comment]
@papou84 Thanks a lot! I will push next release next days. Can we close this issue?

**Comment by Denisll** [comment]
[playmymusic-master.zip](https://github.com/artemanufrij/playmyvideos/files/1718599/playmymusic-master.zip)
Congratulations on the great work, follow the portuguese translation from brazil

**Comment by artemanufrij** [comment]
@Denisll thanks a lot for you support!

could you send just language files you changed? because it's really hard to compare whole project.

It would be very helpful if you could create a PR in https://github.com/artemanufrij/playmymusic

Thank you!

**Comment by Denisll** [comment]
ok

**Comment by Denisll** [comment]
Please, how do I create this file?

**Comment by artemanufrij** [comment]
@Denisll which file do you mean?

here is a simple tutorial for creating PR (Pull Request)
https://rogerdudler.github.io/git-guide/index.html

If you have any questions - feel free to ask :smile:

**Comment by Denisll** [comment]
ok

**Comment by Denisll** [comment]
[pt_BR.po.zip](https://github.com/artemanufrij/playmyvideos/files/1729687/pt_BR.po.zip)

**Comment by Denisll** [comment]
file translated into portuguese

**Comment by artemanufrij** [comment]
@Denisll this file contains translation for music player. I added it already!

**Comment by Denisll** [comment]
sorry, I did the wrong, I'll send the correct one

**Comment by lonicera** [comment]
Hi,
I have translated the pot file into Turkish.

[tr.po.zip](https://github.com/artemanufrij/playmyvideos/files/1734106/tr.po.zip)

**Comment by papou84** [comment]
For now I'm in England and I ain't got much time to translate. As soon as I
get back in France I'll take care of the french and Italian translation. If
someone doesn't do it before I do.

Le 31 janv. 2018 2:07 PM, "Artem Anufrij" <notifications@github.com> a
écrit :

@papou84 <https://github.com/papou84> It would be very helpful! you can use
https://poedit.net/ for translating

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/artemanufrij/playmyvideos/issues/16#issuecomment-361942313>,
or mute the thread

**Comment by artemanufrij** [comment]
@lonicera thank you for your support! Your translation will be released in next few days.

**Comment by lonicera** [comment]
you're welcome. As soon as possible, I would like to translate the 
"Melody" in to Turkish. Thank you very much for such a beautiful apps.

-- 
Yrd. Doç. Dr. Şenol Alan
Zonguldak Bülent Ecevit Üniversitesi Fen-Edebiyat Fakültesi, 
Biyoloji Bölümü
Genel Biyoloji Anabilim Dalı, 67100 İncivez / Zonguldak
Sun, Feb 18, 2018 at 1:03 PM tarihinde, Artem Anufrij 
<notifications@github.com> yazdı:

**Comment by artemanufrij** [comment]
I'm going to close this issue. Just open a new one if needed, or create a PR.
