### ISSUE TITLE
show gala pip when cinema minimize

### ISSUE THREAD

**Issue by torikulhabib** [artemanufrij/playmyvideos#23]
show gala pip when cinema minimize

**Comment by worldofpeace** [comment]
How about when cinema is on an unfocused workspace also?

**Comment by artemanufrij** [comment]
Hey guys, I'm not really sure what you mean _(I'm not a native speaker)_ …

**Comment by artemanufrij** [comment]
PS: if you mean Picture in Picture plugin from donadigo, so it will be shipped with the next gala release.

**Comment by torikulhabib** [comment]
yes gala-pip plugin donadigo.
I imagine the beauty of a video player that can run the gala-pip automatically without manually capturing the screen. I imagine the automatice show gala-pip or automatically captures the cinema screen when cinema is first played. then if there is a change screen cinema whether it is in the drag or in maximize the gala-pip will capture back the screen cinema. or gala-pip screen capture when cinema is minimized. I imagine how hard it is to make such code but I'm sure mr. donadigo and mr @artemanufrij   can make it.

**Comment by worldofpeace** [comment]
So you mean the Picture in Picture plugin but we don't have to select the window and all that crap.
Automatic? Like in mac os https://www.youtube.com/watch?v=5RdLDRDW_kk

**Comment by artemanufrij** [comment]
@worldofpeace that's cool... I will implement it, after gala release. Maybe @donadigo can help me. I will ping him.

**Comment by torikulhabib** [comment]
https://www.omgubuntu.co.uk/2018/07/enable-google-chrome-picture-in-picture
