### ISSUE TITLE
Optimize graphic like MPV

### ISSUE THREAD

**Issue by torikulhabib** [artemanufrij/playmyvideos#24]
I hope there is optimize graphic like mpv
maybe you can redistribute from this source.
https://mpv.io/
https://github.com/mpv-player/mpv

![screenshot from 2018-04-10 13-29-42](https://user-images.githubusercontent.com/26135527/38601595-5c99c8aa-3d92-11e8-8dec-922d4b6903b0.png)
![screenshot from 2018-04-10 13-27-09](https://user-images.githubusercontent.com/26135527/38601621-6f740dc8-3d92-11e8-934f-2c4835d7a9d6.png)

**Comment by artemanufrij** [comment]
Hey @torikulhabib thank you for your feedback. Honestly I didn't understand what you mean :man_shrugging:

**Comment by torikulhabib** [comment]
I hope the colors are generated like mpv
I run mpv and cinema along with the colors produced by mpv brighter
