### ISSUE TITLE
App should use "Play my videos" as the name

### ISSUE THREAD

**Issue by Philip-Scott** [artemanufrij/playmyvideos#4]
Instead of using a generic name, you should use your Play my videos name on the appinfo and desktop file :) 

This will make your app more unique, as well as not make it sound like it's one of the default apps

**Comment by worldofpeace** [comment]
I think his goal is to put the default media apps into obsolescence. :)

**Comment by Philip-Scott** [comment]
Which is a bit sad since he was also a contributor to the default Video player app in elementary ;) 

but regardless, i think it's good practice to not use generic names if possible (and the app is already registered as playmyvideos anyways)

**Comment by artemanufrij** [comment]
New generic was changed -> "Cinema"
